---
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: tmatwood/gitlab-runner-base

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. This step sets up Docker Buildx, a Docker command-line interface (CLI) plug-in for building multi-architecture images.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Setup QEMU for multi-architecture builds on amd64 host machines
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # 4. Setup Homebrew
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
          
      # 5. Install GitVersion
      - name: Install GitVersion
        run: brew install gitversion
      
      # 6. Get Version and Short SHA
      - name: Get version and short SHA
        id: version
        run: |
          echo "VERSION=$(gitversion /showvariable MajorMinorPatch)" >> $GITHUB_ENV
          echo "SHORTSHA=$(gitversion /showvariable ShortSha)" >> $GITHUB_ENV

      # 7. Log Version
      - name: Log version
        run: echo "Building version ${{ env.VERSION }}-${{ env.SHORTSHA }}."

      # 7. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Docker build
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.SHORTSHA }}
            ${{ env.IMAGE_NAME }}:latest

      # 8. Install container-structure-test
      - name: Install Container-Structure-Test
        run: brew install container-structure-test

      # 9. Run container structure tests using the bash script in the project root
      - name: Container Structure Tests
        run: . ./run_tests.sh
        
      # 10. Run container structure tests
      - name: Container Structure Tests
        uses: brpaz/structure-tests-action@v1.1.2
        with:
          # The Docker image to test
          image: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.SHORTSHA }}
          # Path to the config file
          configFile: tests.yml # optional, default is structure-tests.yaml
          
      # 11. Push Docker Image (Only if Tests Pass)
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-${{ env.SHORTSHA }}
          docker push ${{ env.IMAGE_NAME }}:latest
